// Generated by CoffeeScript 1.8.0
(function() {
  var app, express;

  express = require('express.io');

  app = express();

  app.http().io();

  app.io.route('join', function(req) {
    return req.io.join(req.data.room);
  });

  app.io.route('leave', function(req) {
    return req.io.leave(req.data.room);
  });

  app.io.route('send', function(req) {
    var data, id;
    data = req.data;
    id = data.room;
    delete data.room;
    return app.io.room(id).broadcast('recv', data);
  });

  app.use(express["static"]('./downloads'));

  app.listen(5555);

}).call(this);
