// Generated by CoffeeScript 1.8.0
(function() {
  var app, express;

  express = require('express.io');

  app = express();

  app.http().io();

  app.io.route('join', function(req) {
    var id;
    if (!req.data.room) {
      return;
    }
    id = req.data.room;
    req.io.join(id);
    return app.io.room(id).broadcast('rcv', {
      joined: req.data.sender
    });
  });

  app.io.route('leave', function(req) {
    var id;
    if (!req.data.room) {
      return;
    }
    id = req.data.room;
    req.io.leave(id);
    return app.io.room(id).broadcast('rcv', {
      left: req.data.sender
    });
  });

  app.io.route('send', function(req) {
    var data, id;
    data = req.data;
    id = data.room;
    delete data.room;
    return app.io.room(id).broadcast('rcv', data);
  });

  app.use(express["static"]('./public'));

  app.listen(5556);

}).call(this);
