// Generated by CoffeeScript 1.8.0
(function() {
  var Firebase, app, db, express;

  express = require('express.io');

  app = express();

  app.http().io();

  Firebase = require('firebase');

  db = new Firebase('https://fiery-fire-1444.firebaseio.com/');

  app.io.route('proxy', function(req) {
    var _ref;
    if (((_ref = req.data) != null ? _ref.c : void 0) != null) {
      return req.io.route(req.data.c, req.data);
    }
  });

  app.io.route('join', function(req) {
    if (!req.data.r) {
      return;
    }
    req.io.join(req.data.r);
    return app.io.room(req.data.r).broadcast('rcv', {
      joined: req.data.v,
      channel: req.data.r
    });
  });

  app.io.route('leave', function(req) {
    if (!req.data.r) {
      return;
    }
    return req.io.leave(req.data.r);
  });

  app.io.route('send', function(req) {
    if (!req.data.r) {
      return;
    }
    return app.io.room(req.data.r).broadcast('rcv', req.data);
  });

  app.io.route('set', function(req) {
    return db.set(req.data);
  });

  app.use(express["static"]('./public'));

  app.listen(5556);

}).call(this);
